quote page
GSG-FC02/Library-project pull request #19
Opened 2021-04-12 10:56 UTC by alaa521

create HTML and CSS to quote page
add js to about section

2021-04-12 12:19 UTC, amjad573 approved these changes, later dismissed

2021-04-13 04:54 UTC, AlaaTaima commented on qoute/style.css
> +}
**add the property `position : relative` to fix footer style at the mobile screen**

2021-04-13 04:55 UTC, AlaaTaima commented on qoute/index.html
> +    <title>Document</title>
**change the title here to the real page name.**

2021-04-13 04:56 UTC, AlaaTaima commented on qoute/index.html
> +    </div>
**use the semantic element `section` here to wrap this part instead of `div`**

2021-04-13 04:57 UTC, AlaaTaima commented on qoute/index.html
> +    <!-- Quote section end -->
**As the previous comment 👆**

**use the semantic element `section` here to wrap this part instead of `div`**

2021-04-13 04:59 UTC, AlaaTaima commented on qoute/style.css
> +    position: relative;
delete it.

2021-04-13 05:03 UTC, AlaaTaima requested changes
**Good Job 👍** 

* but, there are some points that would be awesome to get enhanced , follow the next 
   comments 👇

2021-04-14 14:18 UTC, AlaaTaima approved these changes

2021-04-14 14:18 UTC, merged